/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Connexion;
import Controller.ConnexionSQL;
import Model.Employe;
import Model.Flight;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author zack
 */
public class EmployePage extends javax.swing.JFrame {

    Employe user ; 
    
    
    public EmployePage() {
        initComponents();
        
        
        
        
        ////////////////////////////
        ConnexionPage.setVisible(true);
        CustomerDataPage.setVisible(false);
        UpdateFlightsPage.setVisible(false);
        BookedFlightPage.setVisible(false);
        MenuBooked.setVisible(false);
        MenuCustomer.setVisible(false);
        MenuUpdate.setVisible(false);  
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ConnexionPage = new javax.swing.JPanel();
        emailTextField = new javax.swing.JFormattedTextField();
        PasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        UpdateFlightsPage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Flights = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        depart = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Destination = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Time = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        messageFlights = new javax.swing.JLabel();
        CustomerDataPage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustomersTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        BookedflightsTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        BookedFlightPage = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        ToolsPanel = new javax.swing.JPanel();
        MenuUpdate = new javax.swing.JPanel();
        UpPanel = new javax.swing.JLabel();
        MenuCustomer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        MenuBooked = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        MenujPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConnexionPage.setBackground(new java.awt.Color(255, 255, 255));

        emailTextField.setText("Email ID ");
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTextFieldMouseClicked(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        PasswordField1.setText("jPasswordField1");
        PasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordField1MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /44948.png")); // NOI18N

        messageLabel.setForeground(new java.awt.Color(51, 51, 255));
        messageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messageLabelMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /email.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /padlock.png")); // NOI18N

        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        message.setForeground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout ConnexionPageLayout = new javax.swing.GroupLayout(ConnexionPage);
        ConnexionPage.setLayout(ConnexionPageLayout);
        ConnexionPageLayout.setHorizontalGroup(
            ConnexionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConnexionPageLayout.createSequentialGroup()
                .addGap(0, 92, Short.MAX_VALUE)
                .addGroup(ConnexionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ConnexionPageLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConnexionPageLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ConnexionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))))
                .addGap(164, 164, 164))
            .addGroup(ConnexionPageLayout.createSequentialGroup()
                .addGroup(ConnexionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConnexionPageLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(messageLabel))
                    .addGroup(ConnexionPageLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConnexionPageLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConnexionPageLayout.setVerticalGroup(
            ConnexionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConnexionPageLayout.createSequentialGroup()
                .addGroup(ConnexionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConnexionPageLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(ConnexionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConnexionPageLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        jLayeredPane1.add(ConnexionPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 490));

        UpdateFlightsPage.setBackground(new java.awt.Color(255, 255, 255));
        UpdateFlightsPage.setForeground(new java.awt.Color(204, 204, 204));

        Flights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Flights.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Flights.setSelectionBackground(new java.awt.Color(255, 153, 0));
        Flights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Flights);

        jLabel8.setBackground(new java.awt.Color(255, 153, 0));
        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel8.setText("Flights");

        depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /Sans titre.png")); // NOI18N
        jLabel9.setText("Depart");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /Sans titre1.png")); // NOI18N
        jLabel10.setText("Destination ");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /time.png")); // NOI18N
        jLabel11.setText("  Time");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /dollar.png")); // NOI18N
        jLabel12.setText("  Price");

        jButton1.setText("ADD ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Uptade");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /plane.png")); // NOI18N
        jLabel1.setText("  Number");

        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /calendar.png")); // NOI18N
        jLabel4.setText("  Date");

        javax.swing.GroupLayout UpdateFlightsPageLayout = new javax.swing.GroupLayout(UpdateFlightsPage);
        UpdateFlightsPage.setLayout(UpdateFlightsPageLayout);
        UpdateFlightsPageLayout.setHorizontalGroup(
            UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateFlightsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateFlightsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageFlights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateFlightsPageLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateFlightsPageLayout.createSequentialGroup()
                .addGroup(UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateFlightsPageLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateFlightsPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depart, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Destination, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateFlightsPageLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(UpdateFlightsPageLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateFlightsPageLayout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        UpdateFlightsPageLayout.setVerticalGroup(
            UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateFlightsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(UpdateFlightsPageLayout.createSequentialGroup()
                        .addComponent(messageFlights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(UpdateFlightsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(UpdateFlightsPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 490));

        CustomerDataPage.setBackground(new java.awt.Color(255, 255, 255));

        CustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CustomersTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        CustomersTable.setSelectionBackground(new java.awt.Color(255, 153, 0));
        CustomersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustomersTable.setShowHorizontalLines(false);
        CustomersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomersTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CustomersTable);

        BookedflightsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BookedflightsTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        BookedflightsTable.setSelectionBackground(new java.awt.Color(255, 153, 0));
        BookedflightsTable.setShowGrid(false);
        jScrollPane3.setViewportView(BookedflightsTable);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel13.setText("Customers");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel14.setText("Booked Flights ");

        jButton4.setText("Delete Customer");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Delete Booked Flights");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerDataPageLayout = new javax.swing.GroupLayout(CustomerDataPage);
        CustomerDataPage.setLayout(CustomerDataPageLayout);
        CustomerDataPageLayout.setHorizontalGroup(
            CustomerDataPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerDataPageLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerDataPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CustomerDataPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(CustomerDataPageLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerDataPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(209, 209, 209))
        );
        CustomerDataPageLayout.setVerticalGroup(
            CustomerDataPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerDataPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(CustomerDataPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPane1.add(CustomerDataPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 490));

        BookedFlightPage.setBackground(new java.awt.Color(153, 255, 153));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout BookedFlightPageLayout = new javax.swing.GroupLayout(BookedFlightPage);
        BookedFlightPage.setLayout(BookedFlightPageLayout);
        BookedFlightPageLayout.setHorizontalGroup(
            BookedFlightPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookedFlightPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        BookedFlightPageLayout.setVerticalGroup(
            BookedFlightPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookedFlightPageLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jLayeredPane1.add(BookedFlightPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 490));

        ToolsPanel.setBackground(new java.awt.Color(255, 153, 0));
        ToolsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        MenuUpdate.setBackground(new java.awt.Color(255, 255, 255));

        UpPanel.setBackground(new java.awt.Color(0, 0, 0));
        UpPanel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        UpPanel.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /plane.png")); // NOI18N
        UpPanel.setText("     Update flights");
        UpPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuUpdateLayout = new javax.swing.GroupLayout(MenuUpdate);
        MenuUpdate.setLayout(MenuUpdateLayout);
        MenuUpdateLayout.setHorizontalGroup(
            MenuUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuUpdateLayout.createSequentialGroup()
                .addComponent(UpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MenuUpdateLayout.setVerticalGroup(
            MenuUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        MenuCustomer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /user copie.png")); // NOI18N
        jLabel6.setText("    Customers Data");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuCustomerLayout = new javax.swing.GroupLayout(MenuCustomer);
        MenuCustomer.setLayout(MenuCustomerLayout);
        MenuCustomerLayout.setHorizontalGroup(
            MenuCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuCustomerLayout.setVerticalGroup(
            MenuCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        MenuBooked.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /dollar.png")); // NOI18N
        jLabel7.setText("    Booked flights");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuBookedLayout = new javax.swing.GroupLayout(MenuBooked);
        MenuBooked.setLayout(MenuBookedLayout);
        MenuBookedLayout.setHorizontalGroup(
            MenuBookedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuBookedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuBookedLayout.setVerticalGroup(
            MenuBookedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        MenujPanel10.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout MenujPanel10Layout = new javax.swing.GroupLayout(MenujPanel10);
        MenujPanel10.setLayout(MenujPanel10Layout);
        MenujPanel10Layout.setHorizontalGroup(
            MenujPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );
        MenujPanel10Layout.setVerticalGroup(
            MenujPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ToolsPanelLayout = new javax.swing.GroupLayout(ToolsPanel);
        ToolsPanel.setLayout(ToolsPanelLayout);
        ToolsPanelLayout.setHorizontalGroup(
            ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuBooked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenujPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ToolsPanelLayout.setVerticalGroup(
            ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolsPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(MenuUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(MenuCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuBooked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenujPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ToolsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addComponent(ToolsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMouseClicked

        emailTextField.setText("");

    }//GEN-LAST:event_emailTextFieldMouseClicked

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void PasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordField1MouseClicked
        PasswordField1.setText("");

    }//GEN-LAST:event_PasswordField1MouseClicked

    private void messageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageLabelMouseClicked
        
        dispose();
    }//GEN-LAST:event_messageLabelMouseClicked

    private void departActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departActionPerformed

    private void UpPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpPanelMouseClicked
       //Uptade flight buttoon 
       
        ConnexionPage.setVisible(false);
        UpdateFlightsPage.setVisible(true);
        CustomerDataPage.setVisible(false);
        BookedFlightPage.setVisible(false);
        
    }//GEN-LAST:event_UpPanelMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            /// Customer date  button page
            CustomersTable.setModel(DbUtils.resultSetToTableModel(user.getCustomer()));
            
        } catch (Exception ex) { 
            
            Logger.getLogger(EmployePage.class.getName()).log(Level.SEVERE, null, ex);
            
        }
         
      ///////////////////////////
        ConnexionPage.setVisible(false);
        CustomerDataPage.setVisible(true);
        UpdateFlightsPage.setVisible(false);
        BookedFlightPage.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       ///Booked Flight PAge 
        ConnexionPage.setVisible(false);
        CustomerDataPage.setVisible(false);
        UpdateFlightsPage.setVisible(false);
        BookedFlightPage.setVisible(true);
        
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // Button connexion 
        String email , password ;
        
        email = emailTextField.getText();
        password = PasswordField1.getText(); 
        
        try {
            if(new Connexion().LoginEmploye(email,password) == true ) {
                
                ConnexionPage.setVisible(false);
                UpdateFlightsPage.setVisible(true);              
                MenuBooked.setVisible(true);
                MenuCustomer.setVisible(true);
                MenuUpdate.setVisible(true);
                
                user = new Connexion().setEmploye(email);
                System.out.print(user.getName());
                
                Flights.setModel(DbUtils.resultSetToTableModel(user.getFlights()));
                               
                
            }else {
                
                message.setText("Please try again !");
                
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployePage.class.getName()).log(Level.SEVERE, null, ex);
           
        }
        
        
        
        
    }//GEN-LAST:event_loginMouseClicked

    private void FlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsMouseClicked
        // Table of all the flights 
         int row = Flights.getSelectedRow();
         String numberfly = (String) Flights.getModel().getValueAt(row,0);
         
        try {
            
            user.setFlights(numberfly);
            depart.setText(user.selectedFlights.getdepart());
            Destination.setText(user.selectedFlights.getdestination());
            Time.setText(user.selectedFlights.getTime());
            price.setText(String.valueOf(user.selectedFlights.getPrice()));
            number.setText(user.selectedFlights.getNumber());
            Date.setText(user.selectedFlights.getDate());
             
            
        } catch (Exception ex) {
            Logger.getLogger(EmployePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_FlightsMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Add flight button 
        String depart,Destination,time,date,number;
        double price ; 
        
       
        depart = this.depart.getText();
        Destination = this.Destination.getText();
        time =  Time.getText();
        
        price = Double.parseDouble(this.price.getText());
        number = this.number.getText();
        date = this.Date.getText();
        
   if(number.isEmpty()  || depart.isEmpty() || Destination.isEmpty() || time.isEmpty() ||  date.isEmpty() )
    messageFlights.setText("Plese try again");
   else {
           
       Flight flight = new Flight(depart,Destination,time,number,date,price);
       messageFlights.setText("Flights has been added ");
       try {
           
            user.addFlights(flight);
            Flights.setModel(DbUtils.resultSetToTableModel(user.getFlights()));
            
            
        } catch (Exception ex) {
            Logger.getLogger(EmployePage.class.getName()).log(Level.SEVERE, null, ex);
            messageFlights.setText(ex.getMessage());
        }
           
    }//GEN-LAST:event_jButton1MouseClicked
}
    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // boutton of update flights ;        
        String depart,Destination,time,date,number;
        double price ; 
        
       
        depart = this.depart.getText();
        Destination = this.Destination.getText();
        time =  Time.getText();
        
        price = Double.parseDouble(this.price.getText());
        number = this.number.getText();
        date = this.Date.getText();
        
        if(number.isEmpty()  || depart.isEmpty() || Destination.isEmpty() || time.isEmpty() ||  date.isEmpty() )
        messageFlights.setText("Plese try again");
        else {
            
        Flight flight = new Flight(depart,Destination,time,number,date,price);
        
        messageFlights.setText("Flights has been updtadeted ");
        
            try {
                
                user.UpdateFlights(flight);
                Flights.setModel(DbUtils.resultSetToTableModel(user.getFlights()));
                
            } catch (Exception ex) {
                
                Logger.getLogger(EmployePage.class.getName()).log(Level.SEVERE, null, ex);
                messageFlights.setText(ex.getMessage());
                
            }
        
        
         }
        
        
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
            // Delete button flight
            user.DeleteFlights();
            messageFlights.setText("Operation Succes "); 
            Flights.setModel(DbUtils.resultSetToTableModel(user.getFlights()));
                       
        } catch (Exception ex){
            
            messageFlights.setText(ex.getMessage());
            Logger.getLogger(EmployePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
          
    }//GEN-LAST:event_jButton3MouseClicked

    private void CustomersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersTableMouseClicked
        // clicked customers table 
        int row = CustomersTable.getSelectedRow();
        int id_customer = (int) CustomersTable.getModel().getValueAt(row,5);
       

        try {
            
            BookedflightsTable.setModel(DbUtils.resultSetToTableModel(user.getBookedFlight(id_customer)));
           // CustomersTable.setModel(DbUtils.resultSetToTableModel(user.getCustomer()));
           
            
        } catch (Exception ex) {
            Logger.getLogger(EmployePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }//GEN-LAST:event_CustomersTableMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // Button to delete customer 
         int row = CustomersTable.getSelectedRow();
         int id_customer = (int) CustomersTable.getModel().getValueAt(row,5);
         
        try {
            user.deleteCustomer(id_customer);
            CustomersTable.setModel(DbUtils.resultSetToTableModel(user.getCustomer()));
            
        } catch (Exception ex) {
            Logger.getLogger(EmployePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
       
          // Button delete booked flight
            
            int row = BookedflightsTable.getSelectedRow();
            int id_customer = (int) BookedflightsTable.getModel().getValueAt(row,1);
            String number = (String) BookedflightsTable.getModel().getValueAt(row,2);
           
         try {   
             
            user.deleteFlights(id_customer, number);
            BookedflightsTable.setModel(DbUtils.resultSetToTableModel(user.getBookedFlight(id_customer)));
            
        } catch (Exception ex) {
            Logger.getLogger(EmployePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookedFlightPage;
    private javax.swing.JTable BookedflightsTable;
    private javax.swing.JPanel ConnexionPage;
    private javax.swing.JPanel CustomerDataPage;
    private javax.swing.JTable CustomersTable;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Destination;
    private javax.swing.JTable Flights;
    private javax.swing.JPanel MenuBooked;
    private javax.swing.JPanel MenuCustomer;
    private javax.swing.JPanel MenuUpdate;
    private javax.swing.JPanel MenujPanel10;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JTextField Time;
    private javax.swing.JPanel ToolsPanel;
    private javax.swing.JLabel UpPanel;
    private javax.swing.JPanel UpdateFlightsPage;
    private javax.swing.JTextField depart;
    private javax.swing.JFormattedTextField emailTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton login;
    private javax.swing.JLabel message;
    private javax.swing.JLabel messageFlights;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField number;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
