/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.CheckoutController;
import Controller.ConnexionSQL;
import Controller.FlightsController;
import Model.Company;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author zack
 */
public final class mainPage extends javax.swing.JFrame {

 Company myCompany = new Company();
 boolean onewayselected = false ; 
    
        
    public mainPage() {
        initComponents();
        setResearchTable();
        
        
        /// mask all the panel  
       ResultPanel.setVisible(false);
       CheckoutPanel.setVisible(false);
       PAIEMENTPANEL.setVisible(false);
       ResultReturnPanel.setVisible(false);
           
        
    }
    
    public void setResearchTable(){ // set the header of the Jtable
        
        JTableHeader header = ResulteTab.getTableHeader(); 
        header.setFont(new Font("Tahome",Font.BOLD,14));
        
        JTableHeader header4 = ResulteTab1.getTableHeader();
        header4.setFont(new Font("Tahome",Font.BOLD,14));
        
        JTableHeader header1 = DEPTAB.getTableHeader();
        header1.setFont(new Font("Tahome",Font.BOLD,14));
       
        
        JTableHeader header2 = ARVTAB1.getTableHeader();
        header2.setFont(new Font("Tahome",Font.BOLD,14));
        
        //set default value of the nbr of personne
        nbrofpass.setValue(1);
        
         
        
    }
    
    public void user(){
        
        myCompany.setuser();
        String name = myCompany.getNameuser(); 
        username.setText("Hello  " + name );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        BackgroundPanel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        ResearchPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        Cityofdep1 = new javax.swing.JTextField();
        CityofAriv1 = new javax.swing.JTextField();
        nbrofpass = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        DepartDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        PanelOneway1 = new javax.swing.JPanel();
        ReturnDate = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        ResultPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResulteTab = new javax.swing.JTable();
        CheckoutPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ROADFLYPANEL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ARVTAB1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        nbrofpersonne = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DEPTAB = new javax.swing.JTable();
        ResultReturnPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ResulteTab1 = new javax.swing.JTable();
        PAIEMENTPANEL = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToolsPanel.setBackground(new java.awt.Color(255, 153, 0));

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /user.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /home-2.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        username.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("MR TOZY ZAKARIA");

        javax.swing.GroupLayout ToolsPanelLayout = new javax.swing.GroupLayout(ToolsPanel);
        ToolsPanel.setLayout(ToolsPanelLayout);
        ToolsPanelLayout.setHorizontalGroup(
            ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolsPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ToolsPanelLayout.setVerticalGroup(
            ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolsPanelLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ToolsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        getContentPane().add(ToolsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 100));

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        ResearchPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        Cityofdep1.setText("Paris");
        Cityofdep1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cityofdep1MouseClicked(evt);
            }
        });
        Cityofdep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cityofdep1ActionPerformed(evt);
            }
        });

        CityofAriv1.setText("Casablanca");
        CityofAriv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CityofAriv1MouseClicked(evt);
            }
        });
        CityofAriv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityofAriv1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Number of passengers");

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        DepartDate.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Depart");

        PanelOneway1.setBackground(new java.awt.Color(0, 0, 0));

        ReturnDate.setBackground(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Return");

        javax.swing.GroupLayout PanelOneway1Layout = new javax.swing.GroupLayout(PanelOneway1);
        PanelOneway1.setLayout(PanelOneway1Layout);
        PanelOneway1Layout.setHorizontalGroup(
            PanelOneway1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOneway1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelOneway1Layout.setVerticalGroup(
            PanelOneway1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOneway1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(PanelOneway1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DepartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addComponent(PanelOneway1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DepartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelOneway1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /Sans titre.png")); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon("/Users/zack/NetBeansProjects/Project/pic /Sans titre1.png")); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Cityofdep1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CityofAriv1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nbrofpass, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(Cityofdep1))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(CityofAriv1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nbrofpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(51, 0, 51));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ROUND TRIP");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 153, 0));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ONE WAY");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel14.setBackground(new java.awt.Color(204, 0, 0));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("SEARCH");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(90, 90, 90))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ResearchPanel1Layout = new javax.swing.GroupLayout(ResearchPanel1);
        ResearchPanel1.setLayout(ResearchPanel1Layout);
        ResearchPanel1Layout.setHorizontalGroup(
            ResearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResearchPanel1Layout.createSequentialGroup()
                .addGroup(ResearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ResearchPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResearchPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ResearchPanel1Layout.setVerticalGroup(
            ResearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResearchPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ResearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        ResultPanel.setBackground(new java.awt.Color(255, 255, 255));
        ResultPanel.setPreferredSize(new java.awt.Dimension(737, 310));

        ResulteTab.setAutoCreateRowSorter(true);
        ResulteTab.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ResulteTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Paris", "Miami", "12:00", "AT 789", "800$"},
                {"Paris", "New York", "12:30", "AT 932", "300$"},
                {"Lisbone", "Madrid", "14:10", "AT 639", "100$"},
                {"Barcelona", "Paris", "17:45", "AT 999", "400$"},
                {"Milan", "Berlin", "20:00", "AT 213", "290$"},
                {"Rome", "Paris", "21:00", "AT 200", "499$"},
                {"Marrackech", "Lyon", "13:00", "AT 390", "299$"},
                {"Lyon", "Marseille", "12:00", "AT 888", "320$"},
                {"Malmo", "Paris", "23:00", "AT 700", "400$"},
                {"Laos", "Tunis", "00:00", "AT 523", "120$"}
            },
            new String [] {
                "DEPART", "DESTINATION", "TIME", "FLIGHT NO.", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ResulteTab.setAutoscrolls(false);
        ResulteTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ResulteTab.setFocusTraversalKeysEnabled(false);
        ResulteTab.setFocusable(false);
        ResulteTab.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ResulteTab.setOpaque(false);
        ResulteTab.setRequestFocusEnabled(false);
        ResulteTab.setRowHeight(50);
        ResulteTab.setSelectionBackground(new java.awt.Color(255, 153, 51));
        ResulteTab.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ResulteTab.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ResulteTab.setShowGrid(false);
        ResulteTab.getTableHeader().setResizingAllowed(false);
        ResulteTab.getTableHeader().setReorderingAllowed(false);
        ResulteTab.setUpdateSelectionOnSort(false);
        ResulteTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResulteTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ResulteTab);
        if (ResulteTab.getColumnModel().getColumnCount() > 0) {
            ResulteTab.getColumnModel().getColumn(0).setResizable(false);
            ResulteTab.getColumnModel().getColumn(1).setResizable(false);
            ResulteTab.getColumnModel().getColumn(2).setResizable(false);
            ResulteTab.getColumnModel().getColumn(3).setResizable(false);
            ResulteTab.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout ResultPanelLayout = new javax.swing.GroupLayout(ResultPanel);
        ResultPanel.setLayout(ResultPanelLayout);
        ResultPanelLayout.setHorizontalGroup(
            ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        ResultPanelLayout.setVerticalGroup(
            ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 223, Short.MAX_VALUE))
        );

        CheckoutPanel.setBackground(new java.awt.Color(255, 255, 255));
        CheckoutPanel.setPreferredSize(new java.awt.Dimension(737, 310));
        CheckoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("000");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 10, 70, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EUR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 70, 40));

        CheckoutPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 274, 190, -1));

        ROADFLYPANEL.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("RETURN FLIGHT");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setEnabled(false);

        ARVTAB1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ARVTAB1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Paris", "Casablanca", "12:00", "AT788", "900"}
            },
            new String [] {
                "DEPART", "DESTINATION", "TIME", "FLIGHT NO.", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ARVTAB1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        ARVTAB1.setCellSelectionEnabled(true);
        ARVTAB1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        ARVTAB1.setEnabled(false);
        ARVTAB1.setFocusTraversalKeysEnabled(false);
        ARVTAB1.setFocusable(false);
        ARVTAB1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ARVTAB1.setOpaque(false);
        ARVTAB1.setRequestFocusEnabled(false);
        ARVTAB1.setRowHeight(45);
        ARVTAB1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        ARVTAB1.setShowHorizontalLines(false);
        ARVTAB1.setShowVerticalLines(false);
        ARVTAB1.setUpdateSelectionOnSort(false);
        ARVTAB1.setVerifyInputWhenFocusTarget(false);
        jScrollPane4.setViewportView(ARVTAB1);
        ARVTAB1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout ROADFLYPANELLayout = new javax.swing.GroupLayout(ROADFLYPANEL);
        ROADFLYPANEL.setLayout(ROADFLYPANELLayout);
        ROADFLYPANELLayout.setHorizontalGroup(
            ROADFLYPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ROADFLYPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ROADFLYPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        ROADFLYPANELLayout.setVerticalGroup(
            ROADFLYPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ROADFLYPANELLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        CheckoutPanel.add(ROADFLYPANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 136, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 51, 51));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("DEPARTING FLIGHT");
        CheckoutPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        nbrofpersonne.setText("Total price for 1 passenger");
        CheckoutPanel.add(nbrofpersonne, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CheckoutPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setEnabled(false);

        DEPTAB.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        DEPTAB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Paris", "Casablanca", "12:00", "AT788", "900"}
            },
            new String [] {
                "DEPART", "DESTINATION", "TIME", "FLIGHT NO.", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DEPTAB.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        DEPTAB.setCellSelectionEnabled(true);
        DEPTAB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DEPTAB.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        DEPTAB.setEnabled(false);
        DEPTAB.setFocusTraversalKeysEnabled(false);
        DEPTAB.setFocusable(false);
        DEPTAB.setIntercellSpacing(new java.awt.Dimension(0, 0));
        DEPTAB.setOpaque(false);
        DEPTAB.setRequestFocusEnabled(false);
        DEPTAB.setRowHeight(45);
        DEPTAB.setSelectionBackground(new java.awt.Color(255, 255, 255));
        DEPTAB.setShowHorizontalLines(false);
        DEPTAB.setShowVerticalLines(false);
        DEPTAB.setUpdateSelectionOnSort(false);
        DEPTAB.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(DEPTAB);

        CheckoutPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 720, 62));

        ResultReturnPanel.setBackground(new java.awt.Color(255, 255, 255));
        ResultReturnPanel.setPreferredSize(new java.awt.Dimension(737, 310));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(469, 404));

        ResulteTab1.setAutoCreateRowSorter(true);
        ResulteTab1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ResulteTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ResulteTab1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        ResulteTab1.setFocusTraversalKeysEnabled(false);
        ResulteTab1.setFocusable(false);
        ResulteTab1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ResulteTab1.setMaximumSize(new java.awt.Dimension(2147483647, 500));
        ResulteTab1.setMinimumSize(new java.awt.Dimension(75, 500));
        ResulteTab1.setOpaque(false);
        ResulteTab1.setPreferredSize(new java.awt.Dimension(370, 500));
        ResulteTab1.setRequestFocusEnabled(false);
        ResulteTab1.setRowHeight(50);
        ResulteTab1.setSelectionBackground(new java.awt.Color(255, 153, 51));
        ResulteTab1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ResulteTab1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ResulteTab1.setShowHorizontalLines(false);
        ResulteTab1.setShowVerticalLines(false);
        ResulteTab1.getTableHeader().setReorderingAllowed(false);
        ResulteTab1.setUpdateSelectionOnSort(false);
        ResulteTab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResulteTab1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ResulteTab1);

        javax.swing.GroupLayout ResultReturnPanelLayout = new javax.swing.GroupLayout(ResultReturnPanel);
        ResultReturnPanel.setLayout(ResultReturnPanelLayout);
        ResultReturnPanelLayout.setHorizontalGroup(
            ResultReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultReturnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        ResultReturnPanelLayout.setVerticalGroup(
            ResultReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultReturnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        PAIEMENTPANEL.setBackground(new java.awt.Color(255, 255, 255));
        PAIEMENTPANEL.setPreferredSize(new java.awt.Dimension(737, 310));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("YOUR FLY ARE NOW BOOKED");

        javax.swing.GroupLayout PAIEMENTPANELLayout = new javax.swing.GroupLayout(PAIEMENTPANEL);
        PAIEMENTPANEL.setLayout(PAIEMENTPANELLayout);
        PAIEMENTPANELLayout.setHorizontalGroup(
            PAIEMENTPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAIEMENTPANELLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(91, 91, 91))
        );
        PAIEMENTPANELLayout.setVerticalGroup(
            PAIEMENTPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAIEMENTPANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(132, 132, 132))
        );

        jLayeredPane1.setLayer(ResearchPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ResultPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CheckoutPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ResultReturnPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PAIEMENTPANEL, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PAIEMENTPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(47, Short.MAX_VALUE)
                    .addComponent(ResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(99, 99, 99)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(CheckoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 90, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ResultReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(121, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(PAIEMENTPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(CheckoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ResultReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(176, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cityofdep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cityofdep1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cityofdep1ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        //Buyyon for ROAD TOUR
         PanelOneway1.setVisible(true);
         ROADFLYPANEL.setVisible(true);
         onewayselected=false;
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        //Button for ONE WAY 
        onewayselected = true ; 
        PanelOneway1.setVisible(false);
        ResultReturnPanel.setVisible(false);
        ROADFLYPANEL.setVisible(false);
              
    }//GEN-LAST:event_jLabel17MouseClicked

    
    //Do a research in the data base to get the correct flight 
    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
  
        try {
         
         String tmp,datedep,dep,arv;
         ResultSet rset = null , rset2 = null;
         
         dep= Cityofdep1.getText(); // get the variables
         arv= CityofAriv1.getText();
         myCompany.numberofperson = (int) nbrofpass.getValue();
         
         
         tmp = String.valueOf(DepartDate.getDate());
         
         String[] date = tmp.split(" ");
         datedep = date[2] + date[1] + date[5] ;
         
         rset = new FlightsController(). GetFlight(dep,arv,datedep);//use the methode to get date
         ResulteTab.setModel(DbUtils.resultSetToTableModel(rset)); 
         
         ///////////////////////////// Road tours selected //////////////////////////////////////
        if(onewayselected == false) {
        //We inverse the deparature and the destination 
        tmp = dep ; 
        dep = arv ; 
        arv = tmp ; 
        
        tmp = String.valueOf(ReturnDate.getDate());
         
         date = tmp.split(" ");
         datedep = date[2] + date[1] + date[5] ;
        
         rset2 = new FlightsController(). GetFlight(dep,arv,datedep); // we display the result in the second 
         ResulteTab1.setModel(DbUtils.resultSetToTableModel(rset2)); 
         
       
         }
            
         ResearchPanel1.setVisible(false);
         ResultPanel.setVisible(true);
         
         
         
     } catch (SQLException ex) {
         
         Logger.getLogger(mainPage.class.getName()).log(Level.SEVERE, null, ex);
         
     }
        
    }//GEN-LAST:event_jLabel18MouseClicked

    private void ResulteTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResulteTabMouseClicked
      
     try {
         
         int row = ResulteTab.getSelectedRow();
         String numberfly = (String) ResulteTab.getModel().getValueAt(row,0);
         System.out.print(numberfly);
         
         myCompany.addFlight(numberfly,0);
         DEPTAB.setModel(DbUtils.resultSetToTableModel(new FlightsController(). GetFlight(numberfly)));
         
         //////////////////////ROAD TOUR ////////////////////////////
         if(onewayselected==false){
             
            ResultPanel.setVisible(false);
            ResultReturnPanel.setVisible(true);
                
         }else {
          
             ResultPanel.setVisible(false);
             CheckoutPanel.setVisible(true); 
             new CheckoutController().calculTotal(myCompany);
             total.setText(Double.toString(myCompany.subTotal));
             nbrofpersonne.setText("FOR "+ myCompany.numberofperson +" PEOPLE") ;
             
         }
             
         
         ///////////////////////////////////////////////////////////
        
         
     } catch (SQLException ex) {
         Logger.getLogger(mainPage.class.getName()).log(Level.SEVERE, null, ex);
     } catch (Exception ex) {
         Logger.getLogger(mainPage.class.getName()).log(Level.SEVERE, null, ex);
     }
     
    }//GEN-LAST:event_ResulteTabMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
     ///Button confirme    
     try {
         myCompany.buy();
         
         new CheckoutPage(myCompany.subTotal,myCompany.Total).setVisible(true);
         
         CheckoutPanel.setVisible(false);
         PAIEMENTPANEL.setVisible(true);
         ResultReturnPanel.setVisible(false);
         
     } catch (Exception ex) {
         Logger.getLogger(mainPage.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
        new ConnexionPage(myCompany.conn).setVisible(true);
        
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       ///Button of the return to the main page      
       //reset 
       myCompany.reset();
       onewayselected = false ; 
       
      
         
       ResultPanel.setVisible(false);
       CheckoutPanel.setVisible(false);
       PAIEMENTPANEL.setVisible(false);
       ResultReturnPanel.setVisible(false);
       ResearchPanel1.setVisible(true);
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
       user();
    }//GEN-LAST:event_formMouseEntered

    private void Cityofdep1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cityofdep1MouseClicked
        
        Cityofdep1.setText("");
        
    }//GEN-LAST:event_Cityofdep1MouseClicked

    private void CityofAriv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityofAriv1ActionPerformed
        // a supptimer
        CityofAriv1.setText("");
        
    }//GEN-LAST:event_CityofAriv1ActionPerformed

    private void CityofAriv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CityofAriv1MouseClicked
        CityofAriv1.setText("");
    }//GEN-LAST:event_CityofAriv1MouseClicked

    private void ResulteTab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResulteTab1MouseClicked
     try {
         ///////////////////ROAD TOUR RESULT ///////////////////
         int row = ResulteTab1.getSelectedRow();
         String numberfly = (String) ResulteTab1.getModel().getValueAt(row,0);
         System.out.print(numberfly);
         
         myCompany.addFlight(numberfly,1);
         ARVTAB1.setModel(DbUtils.resultSetToTableModel(new FlightsController(). GetFlight(numberfly)));
         
         new CheckoutController().calculTotal(myCompany);
         total.setText(Double.toString(myCompany.subTotal));
         nbrofpersonne.setText("FOR "+ myCompany.numberofperson +" PEOPLE") ;
         
         ResultReturnPanel.setVisible(false);
         CheckoutPanel.setVisible(true);
         
     
     
     
     } catch (SQLException ex) {
         Logger.getLogger(mainPage.class.getName()).log(Level.SEVERE, null, ex);
     } catch (Exception ex) {
         Logger.getLogger(mainPage.class.getName()).log(Level.SEVERE, null, ex);
     }
        
        
         
        
        
    }//GEN-LAST:event_ResulteTab1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ARVTAB1;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel CheckoutPanel;
    private javax.swing.JTextField CityofAriv1;
    private javax.swing.JTextField Cityofdep1;
    private javax.swing.JTable DEPTAB;
    private com.toedter.calendar.JDateChooser DepartDate;
    private javax.swing.JPanel PAIEMENTPANEL;
    private javax.swing.JPanel PanelOneway1;
    private javax.swing.JPanel ROADFLYPANEL;
    private javax.swing.JPanel ResearchPanel1;
    private javax.swing.JPanel ResultPanel;
    private javax.swing.JPanel ResultReturnPanel;
    private javax.swing.JTable ResulteTab;
    private javax.swing.JTable ResulteTab1;
    private com.toedter.calendar.JDateChooser ReturnDate;
    private javax.swing.JPanel ToolsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner nbrofpass;
    private javax.swing.JLabel nbrofpersonne;
    private javax.swing.JLabel total;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
